config/routes.rb
Rails.application.routes.draw do
  resources :styles do
    resources :corpses, :path => "payams"
  end
  resources :lines, :except => [:update, :edit] 
  resources :corpses, :path => "payams" do
    member do
      post 'decompose'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :players do
    resources :corpses, :path => "payams"
    resources :lines
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'welcome/about'


  # keep user id out of the visible url
  get 'player' => 'players#show'
end

app/controllers/corpses_controller.rb
class CorpsesController < ApplicationController
  before_action :set_corpse, only: [:show, :edit, :update, :destroy, :decompose]

	def index
    #only display corpses of a particular style that are completed
    if params[:style_id]
      @corpses = Corpse.completed.where(:style_id => params[:style_id])
    else
      #or all completed
		  @corpses = Corpse.completed
    end
    #everything else
    @all_other_corpses = Corpse.all - Corpse.completed
	end

	def new
    #remove orphaned custom styles
    clean_styles
		@corpse = Corpse.new
    @line = @corpse.lines.build
    @style = Style.new
	end

	def create
    @corpse_params = corpse_params
    @corpse_params[:lines_attributes][:"0"][:auth_id] = current_user.id
    @corpse = Corpse.new(@corpse_params)
    #@corpse.lines.last.auth_id = current_user.id
    #check for both selection from dropdown and new entry in text field
    if style_check
      render :new
    elsif @corpse.valid?
      @corpse.save
      #randomly select the next scribe
      @corpse.current_scribe = User.where.not(id: current_user.id).sample.id
      #send_to_next increases counter by 1 and saves
      @corpse.send_to_next
  		redirect_to root_path
    else
      @style = Style.new(:name => corpse_params[:style_attributes][:name])
      render :new
    end
	end

	def show
	end

  def decompose
    @corpse.lines.each do |line|
      line.lose_word
    end
    redirect_to corpse_path(@corpse)
  end

	def edit
      @line = @corpse.lines.build
	end

	def update
    @corpse_params = corpse_params
    @corpse_params[:lines_attributes][:"0"][:auth_id] = current_user.id

		if @corpse.update(@corpse_params)
      if @corpse.counter < 8
        #select next user and increase counter by 1
        @corpse.current_scribe = User.where.not(id: current_user.id).sample.id
        @corpse.send_to_next
      else
        #set current_scribe to nil so it goes to no one and the corpse is scoped to completed
        @corpse.current_scribe = nil
        @corpse.save
      end
			redirect_to root_path
    else
      @line = Line.new(:text => corpse_params[:lines_attributes]["0"][:text])
      render :edit
		end
	end

	def destroy
    @corpse.destroy
    flash[:notice] = "Payam Deleted!!"
    redirect_to root_path
	end

	private

    def set_corpse
    	@corpse = Corpse.find(params[:id])
    end

	def corpse_params
		params.require(:corpse).permit(:style_id, :counter, :title, :current_scribe, :lines_attributes => [:text, :corpse_id, :auth_id, :count], style_attributes: [:name])
  end

  def style_check
    if !corpse_params[:style_id].blank? && !corpse_params[:style_attributes][:name].blank?
      @corpse.style_id = corpse_params[:style_id]
      @style = Style.new(:name => corpse_params[:style_attributes][:name])
      @corpse.errors.add(:style, "must be selected or created--not both")
    #elsif corpse_params[:style_id].blank? && corpse_params[:style_attributes][:name].blank?
    #  @corpse.errors.add(:style, "add a style, ya goof")
    #  @style = Style.new
    end
  end

  def clean_styles
    Style.all.each do |style|
      style.delete if style.corpses.empty? && style.protected == false
    end
  end

end

app/helpers/corpses_helper.rb
module CorpsesHelper
end

app/views/corpses/_completed.html.erb
<div class="container goudy side-plaque">
  <div class="container" style="border-bottom: 1px solid; text-align: center">
    <h2>This payam is called "<%= @corpse.title %>" and it is in the <%= Style.find(@corpse.style_id).name %> style</h2>
  </div>

   <div class="container">
    <p style="font-size: 30px; line-height: 1.8em">
      <% Line.select {|line| line.corpse_id == @corpse.id}.sort_by {|lin| lin.count}.each do |li| %>
        <% case li.count %>
          <% when 1 %>
            <span style="color: #11aaff"><%= li.text %></span>
          <% when 2 %>
            <span style="color: #ff22aa"><%= li.text %></span>
          <% when 3 %>
            <span style="color: #aaff33"><%= li.text %></span>
          <% when 4 %>
            <span style="color: #44aaff"><%= li.text %></span>
          <% when 5 %>
            <span style="color: #ff55aa"><%= li.text %></span>
          <% when 6 %>
            <span style="color: #aaff66"><%= li.text %></span>
          <% when 7 %>
            <span style="color: #77aaff"><%= li.text %></span>
          <% when 8 %>
            <span style="color: #ff88aa"><%= li.text %></span>
          <% else %>
            <span style="color: #111"><%= li.text %></span>
        <% end %>
      <% end %>
    </p>
  </div>

  <div class="container" style="text-align: center">
    <%= button_to "Home", player_path(current_user), {method: :get, class: "btn btn-default"} %>
  </div>
</div>


<div class="flex-container" style="height: 200px; justify-content: center; align-items: flex-end">
  <div class="container">
    <%= button_to "Decompose", decompose_corpse_path(@corpse), {:id => @corpse.id, class: "btn btn-decomp"} %>
  </div>
</div>

app/views/corpses/_form.html.erb
<div class="container goudy text-boxer">
  <%= form_for(@corpse, :html => {:class => "form-horizontal"}) do |f| %>

    <% if @corpse.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@corpse.errors.count, "error") %> stopped this Payam from going forward:</h2>
        <ul>
         <% @corpse.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
        </ul>
       </div>
    <% end %>

    <% if @corpse.counter == 1 %>
      <div class="container" style="border-bottom: 1px dotted; border-color: #dab4e4; padding-bottom: 20px">
        <div class="col-sm-6">
          <p><span class="biginner">P</span>ick a style from a list...</p>
          <div class="form-group col-sm-12">
            <%= f.collection_select(:style_id, Style.all, :id, :name, {:include_blank => "Select a Style"}, :class => "form-control") %>
          </div><!--form-group-->
        </div><!--col-sm-6-->
        <div class="col-sm-6">
          <p><span class="biginner">O</span>r make up a new style.</p>
          <div class="form-group col-sm-12">
            <%= f.fields_for :style, @style do |style_name| %>
              <%= style_name.text_field :name, :placeholder => "Create a new one", :class => "form-control"%>
            <% end %>
          </div><!--form-group-->
        </div><!--col-sm-6-->
      </div><!--container-->
      <div class="container">
        <div class="col-sm-12">
          <p><span class="biginner">P</span>rovide a one-word title to guide the later authors</p>
          <div class="form-group col-sm-6">
            <%= f.text_field :title, :placeholder => "one-word title", class: "form-control" %><br>
          </div>
        </div>
      </div>
    <% else %>
      <div class="container">
        <p>The style of this Payam is <span style="color: #45c467"><%= @corpse.style.name%></span>, and the title is <span style="color: #45c467">"<%=@corpse.title%>"</span>.
      </div>
    <%end%>

    <div class="container" style="border-top: 1px dotted; border-color: #dab4e4; padding-top: 20px">
      <% if @corpse.counter == 1 %>
        <p><span class="biginner">W</span>rite the first line.
      <% else %>
        <p><span class="biginner">S</span>o far, the Payam has <%= @corpse.counter - 1 %>
          <% if @corpse.counter == 2 %>
            author,
          <% else %>
            authors,
          <% end %>
        and you are number <%= @corpse.counter %>.</p>
        <p>The previous author's last five words were:<em><blockquote id="base-purp" style="font-size: 20px">...<%= @corpse.previous_five%></blockquote></em></p>
        <p>Write the next line.
      <% end %>

      <% if @corpse.counter == 8 %>
        This is the last line, so make it count.<p><br>
      <% else %>
        Make it between 10-20 words. The next writer will only see the last 5 words you write.</p><br>
      <% end %>

      <div class="container">
        <div class="form-group">
          <%= f.fields_for :lines, @line do |line| %>

              <% if @corpse.counter < 8 %>
                <%= line.text_field :text, class: "form-control", placeholder: "Think about your last 5 words as they will be what the next author sees..." %><br>
              <% else %>
                <%= line.text_field :text, class: "form-control", placeholder: "These are the last words of the Payam..." %><br>
              <% end %>
                <!-- where the hidden fields were -->
            <% end %>

        </div><!--form-group-->
      </div><!--container-->
    </div><!--container with border-bottom-->
    <%= f.hidden_field :current_scribe, :value => current_user.id %>
    <div class="container">
      <div class="form-group">
        <div class="col-sm-1">
          <%= f.submit "Submit", class: "btn btn-default" %>
        </div>
      </div> <!-- form-group-->
    </div><!--container-->
  <% end %><!--end of form_for-->
</div>

app/views/corpses/edit.html.erb
<%= render 'form' %>

app/views/corpses/index.html.erb
<div class="container text-boxer goudy">
<% if @corpses.empty? %>
  <p><em>None to show yet. Maybe <%= link_to "Start one of your own", new_corpse_path %>?</em></p>
<% else %>

  <% @corpses.each do |corpse| %>
    <p>Check out <span id="base-purp"><%= "#{corpse.title}" %></span> in the <%= link_to "#{corpse.style.name}", corpse_path(corpse) %> style.</p>
  <% end %>

<% end %>
</div>

app/views/corpses/new.html.erb
<%= render 'form' %>

app/views/corpses/show.html.erb
<%= render 'completed' %>