config/routes.rb
Rails.application.routes.draw do
  resources :styles do
    resources :corpses, :path => "payams"
  end
  resources :lines, :except => [:update, :edit] 
  resources :corpses, :path => "payams" do
    member do
      post 'decompose'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :players do
    resources :corpses, :path => "payams"
    resources :lines
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'welcome/about'


  # keep user id out of the visible url
  get 'player' => 'players#show'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container goudy">

    <p class="text-muted">We stand eternally frozen in the unreachable moments of the past, and there we live forever.</p>

  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="brando" href="/welcome/about">About Payam</a>
    </div>
    <div id="navbarCollapse" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
          <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Read Up<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/payams">Public Payams</a></li>
                  <li><a href="/payams/new">Make one of your own</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Styles</li>
                  <li><%= link_to "Funny", style_corpses_path(Style.find_by(:name => "Funny")) %></li>
                  <li><%= link_to "Serious", style_corpses_path(Style.find_by(:name => "Serious")) %></li>
                  <li><%= link_to "Sad", style_corpses_path(Style.find_by(:name => "Sad")) %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path%></li>
          <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a>Hello, <%=current_user.username %>!</a></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to "Edit Info", edit_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <ul>
    	<li>
    		<%= value %>
    	</li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class= "full" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="doulgas">
    <title>Payam</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container-fluid site-wrapper">
      <%= render 'layouts/header' %>
      <div class="container">
        <div class="jumbotron">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div><!--jumbotron-->
      </div><!--container-->
    </div><!--container-fluid site-wrapper-->
    <%= render 'layouts/footer' %>
  </body>
</html>